version: '2.1'

services:
  hepsub:
    container_name: hepsub-apiban
    image: sipcapture/hepsub-apiban:latest
    ports:
      - "18088:18088"
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-hepsub}
      - HOMER_IP=${HOMER_IP:-homer}
      - HOMER_PORT=${HOMER_PORT:-9080}
      - APIBAN_KEY=${APIBAN_KEY:-0000000000000000000000000000000000000000000}
      - HOMER_TOKEN=${HOMER_TOKEN:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
    restart: unless-stopped
