version: '2.1'

services:
  hepsub:
    container_name: hepsub-apiban
    image: sipcapture/hepsub-apiban
    ports:
      - "18088:18088"
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-hepsub}
      - HOMER_IP=${HOMER_IP:-homer}
      - HOMER_PORT=${HOMER_PORT:-9080}
    restart: unless-stopped
